mutation SubscribeToNewsletter($email: String!) {
    subscribeToNewsletter(input: { email: $email, publicationId: "666d4f03c8a425332693a535" }) {
        status
    }
}

query GetPosts {
    publication(host: "blog.nurulhudaapon.com") {
        isTeam
        title
        posts(first: 10) {
            edges {
                node {
                    id
                    coverImage {
                        url
                    }
                    slug
                    subtitle
                    views
                    title
                    brief
                    url
                }
            }
        }
    }
}

query GetPostBySlug($slug: String!) {
    publication(host: "blog.nurulhudaapon.com") {
        post(slug: $slug) {
            id
            slug
            subtitle
            views
            title
            brief
            publishedAt
            coverImage {
                url
            }
            updatedAt
            featuredAt
            content {
                markdown
            }
            url
        }
    }
}
