query GetSimplePosts {
  posts {
    data {
      attributes {
        title
      }
    }
  }
}

query GetSimpleSnippets {
  snippets {
    data {
      attributes {
        title
        slug
      }
    }
  }
}
